### ISSUE TITLE
Feature: Overwrite runArgs in devcontainer.json

### ISSUE THREAD

**Issue by ChiefGokhlayeh** [devcontainers/ci#147]
I run a workflow which involves supplying my host's GPU to the devcontainer. GPU-acceleration is an optional feature inside the devcontainer so it is also able to run in CPU-only mode. For my GitHub Workflows I would therefore like to supply different `runArgs` via `devcontainer.json`. Something like this:

When using devcontainers via vscode:
```jsonc
{
  //...
  // with GPU support (on developer PC)
  "runArgs": [
      "--gpus=all,\"capabilities=compute,utility\"",
  ],
  //...
}
```

And when run with [devcontainers/ci](https://github.com/devcontainers/ci):
```jsonc
{
  //...
  // without GPU support (on GitHub runner)
  "runArgs": [
    // empty or something else
  ],
  //...
}
```

For now I worked around the by manually patching `devcontainer.json` before running the [devcontainers/ci](https://github.com/devcontainers/ci) action.

Here's the workaround:
```yaml
- uses: actions/checkout@v3
- run: sed -i '/"runArgs"\s*:\s*\[/,/]/d' .devcontainer/devcontainer.json # delete entire runArgs block from json
- uses: devcontainers/ci@v0.2
  with:
      runCmd: echo "Hello World"
```

In truth, I would much rather have this as a general vscode devcontainers feature. Something along the lines of "enable GPU pass-through, if available", but up until now I managed to work around the issue (by always having a GPU on every machine).
