### ISSUE TITLE
`undefined` in docker-compose.devcontainer.build-*.yml

### ISSUE THREAD

**Issue by hankei6km** [devcontainers/ci#148]
I am trying with the following repository.
- `devcontainer.json` use docker compose
- A workflow is run with GitHub Actions

https://github.com/hankei6km/test-devcontainers-cli-compose

## cli

Using `@devcontainers/cli` directly from within the workflow will succeed.

https://github.com/hankei6km/test-devcontainers-cli-compose/runs/6874333436?check_suite_focus=true

## ci

Using `devcontainers/ci@v0.2` will result in an error.

https://github.com/hankei6km/test-devcontainers-cli-compose/runs/6874333439?check_suite_focus=true

``` 
  [2196 ms] yaml.scanner.ScannerError: while scanning a simple key
    in "/tmp/docker-compose/docker-compose.devcontainer.build-1655184778637.yml", line 3, column 1
  could not find expected ':'
    in "/tmp/docker-compose/docker-compose.devcontainer.build-1655184778637.yml", line 4, column 17
```

`undefined` was included when `docker-compose.devcontainer.build-1655184778637.yml` was displayed

```yml
services:
  node:
undefined
      cache_from:
        - ghcr.io/hankei6km/h6-dev-containers:node
```

## files

Below are the contents of the related files.

.devcontainer/devcontainer.json
```json
{
  "name": "node",
  "dockerComposeFile": "docker-compose.yml",
  "service": "node",
  "remoteUser": "vscode",
  "workspaceFolder": "/home/vscode/workspace",
  "extensions": ["esbenp.prettier-vscode"],
  "settings": {
    "[typescript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[jsonc]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[html]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
  }
}
```

.devcontainer/docker-compose.yml

```yml
version: '3.8'

services:
  node:
    # image: 'ghcr.io/hankei6km/h6-dev-containers:node'
    build:
      context: .
      dockerfile: Dockerfile
    hostname: node
    user: vscode
    volumes:
      - ../:/home/vscode/workspace
    tty: true
  httpbin:
    image: 'kennethreitz/httpbin:latest'
    hostname: httpbin

```

.devcontainer/Dockerfile
```
FROM ghcr.io/hankei6km/h6-dev-containers:node
```

.github/workflows/test_chk.yaml
```yml
name: test_chk
on:
  push:
    branches:
      - '**'
    tags:
      - '!v*'
  workflow_dispatch:

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        continue-on-error: true
        with:
          imageName: ghcr.io/hankei6km/h6-dev-containers
          imageTag: node
          push: never
          runCmd: |
            npm install
            npm run test

      - name: Print failed files
        run: cat /tmp/docker-compose/docker-compose.devcontainer.build-*.yml
```
