### ISSUE TITLE
Suggestions to simplify image prebuilding

### ISSUE THREAD

**Issue by Chuxel** [devcontainers/ci#150]
In my case, I am using this action to pre-build an image I then use in codespaces and remote - containers.  I do this on a periodic basis for security, and do not need to execute anything in the container.

I was expecting to be able to do this:

```yaml
      - name: Build image
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/chuxel/devpacks/devcontainer
```

However, what I ended up needing to do was this:

```yaml
      - name: Build image
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/chuxel/devpacks/devcontainer
          skipContainerUserIdUpdate: true
          push: always
          runCmd: echo "Image built successfully."
```

Would it be possible to alter the defaults so you didn't need quite so much knowledge of properties to do it?  Otherwise including a clear example for this scenario in the READEME and docs probably makes sense.  //cc @stuartleeks

**Comment by stuartleeks** [comment]
Thanks @Chuxel 

> Ideally if runCmd wasn't specified, it would just skip the container spin up for example.
I agree - this would be a nice addition!

I'm not sure that the `skipContainerUserIdUpdate: true` is needed here as the image that is built/tagged doesn't have the user id update applied to it. That said, I can see it as a minor perf tweak (that wouldn't be relevant if an empty `runCmd` skipped running the container)

So, with the change to skip running if `runCmd` is missing, I think you'd be down to the following:

```yaml
- name: Build image
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/chuxel/devpacks/devcontainer
          push: always
```

The `push` filter is an area that might benefit from more thought. I'm not sure whether it would make sense to always push on `workflow_dispatch` or not. My goal with the filters was to set it up so that `main` branch builds would default to pushing but there are some edge-cases that would probably benefit from calling out in the docs if there aren't ways to smooth them out
