### ISSUE TITLE
Make `imageName` a non-required input

### ISSUE THREAD

**Issue by lsorber** [devcontainers/ci#152]
This example from the [GitHub Action documentation](https://github.com/devcontainers/ci/blob/main/docs/github-action.md) does not work:
```yaml
name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          # Change this to be your CI task/script
          runCmd: yarn test
```
The reason is that `imageName` is a required input.

A solution would be to not make `imageName` a required input. The `push` input already "Defaults to `filter` if `imageName` is set, `never` otherwise."
