### ISSUE TITLE
Incorrect parsing of environment variable when quoted

### ISSUE THREAD

**Issue by irarainey** [devcontainers/ci#168]
I was passing in a URL endpoint as an environment variable to a workflow step to run end-to-end test via Newman, and I was getting a protocol error through by Newman. After some investigation trying to access the same endpoint using wget I noticed that variable being passed in was being parsed incorrectly.

The problem arose when I was calling it like this:

```
- name: Run Tests
  uses: devcontainers/ci@v0.2
  with:
    imageName: ghcr.io/microsoft/my-devcontainer
    runCmd: make run-tests
    imageTag: ${{ env.TAG }}
    env: API_ENDPOINT="https://${{ env.APP_NAME }}.azurewebsites.net"
```

The solution was to remove the quotes around the variable like this:

```
- name: Run Tests
  uses: devcontainers/ci@v0.2
  with:
    imageName: ghcr.io/microsoft/my-devcontainer
    runCmd: make run-tests
    imageTag: ${{ env.TAG }}
    env: API_ENDPOINT=https://${{ env.APP_NAME }}.azurewebsites.net
```

But as a string I would expect it to be able to handle either format.
