### ISSUE TITLE
No support for GitLab CI

### ISSUE THREAD

**Issue by raginjason** [devcontainers/ci#205]
I see instructions on how to build devcontainers with GitHub and Azure DevOps, but nothing for GitLab CI. This may simply be a documentation issue, I don't know. I've attempted to get this working with GitLab CI, but so far have come up short, especially with various docker-in-docker (DinD) issues. Can you provide an example `.gitlab-ci.yml` or some instructions on how to get this working with GitLab CI?

**Comment by stuartleeks** [comment]
Hi @raginjason - at its core, this project is a wrapper around [devcontainers/cli](https://github.com/devcontainers/cli). While this project only has support for GitHub actions/Azure DevOps pipelines, the `devcontainer` CLI can be installed in other environments and used to build and run dev containers. I'm not familiar with GitLab, but assuming that it offers a similar capability for building custom tasks then this project may be a useful reference if you are interested in building that out.

Hope that helps!

**Comment by stuartleeks** [comment]
In a previous team, we started using dev containers in CI as a way to avoid having to keep tools/packages/versions installed in the CI environment in sync with the dev container that we were using for our local dev. That was before the `devcontainers` CLI was created and had some pretty rough edges.

It sounds like there may be an opportunity to give more details on the CI scenario using the `devcontainers` CLI - what sort of issues are you having, and what sort of info would you have found useful?

**Comment by raginjason** [comment]
A example `.gitlab-ci.yml` is really what would have been useful. I kept working on this and this will build a `devcontainer` and push it to GitLab's own container registry:
```yaml
image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

before_script:
  - docker info
  - apk add --update nodejs=16.17.1-r0 npm=8.10.0-r0 python3=3.10.9-r0 make=4.3-r0 g++=11.2.1_git20220219-r2
  - npm install -g @devcontainers/cli

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - devcontainer build --workspace-folder . --push true --image-name ${CI_REGISTRY_IMAGE}:latest
```

Any thoughts on where to include this documentation so that others may benefit from it?
