### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'logs'

### ISSUE THREAD

**Issue by yaozhang09** [devcontainers/ci#257]
v0.3 Action was working till about a week ago.  Now container fails to pass the postcreatecommand after build with the error

```PermissionError: [Errno 13] Permission denied: 'logs'```
```[2023-08-28T17:44:17.307Z] postCreateCommand failed with exit code 2. Skipping any further user-provided commands.```

I've tried pinning it to the latest `devcontainers/ci@v0.3.1900000328` but to no avail.
Our devcontainer.json:
```
{
    "name": "dbt",
    "build": {
		"dockerfile": "../dbt/Dockerfile",
		"args": { "VARIANT": "3.10-bullseye" }
	},
	"workspaceMount": "src=${localWorkspaceFolder},target=/usr/app,type=bind,consistency=cached",
	"mounts": [
        "src=${localEnv:HOME}/.dbt/profiles.yml,target=/home/vscode/.dbt/profiles.yml,type=bind,readonly",
        "src=${localEnv:HOME}/.config/gcloud/application_default_credentials.json,target=/var/secrets/google/client_secrets.json,type=bind,readonly"
    ],
	"workspaceFolder": "/usr/app/dbt",
	"containerEnv": {
        "GOOGLE_APPLICATION_CREDENTIALS": "${localEnv:GOOGLE_APPLICATION_CREDENTIALS:/var/secrets/google/client_secrets.json}",
		"TARGET": "${localEnv:TARGET:dev}",
        "GCP_PROJECT_ID": "${localEnv:GCP_PROJECT_ID:apollo-warehouse-dev}",
        "DBT_PROFILES_DIR": "${localEnv:DBT_PROFILES_DIR:~/.dbt/}",
		"DATASET": "${localEnv:DATASET}"
    },
	"forwardPorts": [
		8000
	],
	"postCreateCommand": "dbt deps && dbt debug && dbt seed && pre-commit install && pre-commit install --hook-type post-checkout && cp target/manifest.json .", //Note: dbt deps is needed here and in Dockerfile so prod airflow works
	"postStartCommand": "git config --global --add safe.directory ${containerWorkspaceFolder}",
	"settings": {
		"terminal.integrated.defaultProfile.linux": "zsh",
        "python.pythonPath": "/usr/local/bin/python",
        "python.languageServer": "Pylance",
        "files.associations": {
            "*.sql": "jinja-sql"
        },
		"dbt.bigquery.projectId": "apollo-warehouse-dev",
		"dbt.bigquery.runnerTheme": "light",
		"sqlfluff.config": "${workspaceFolder}/.sqlfluff",
		"sqlfluff.linter.run": "onSave",
  		"sqlfluff.experimental.format.executeInTerminal": true,
  		"editor.formatOnSave": false
    },
	"remoteUser": "vscode",
	"customizations": {
		"vscode": {
			"extensions": [
				"eamodio.gitlens",
				"mhutchie.git-graph",
				"ms-azuretools.vscode-docker",
				"GitHub.vscode-pull-request-github",
				"MarkLarah.pre-commit-vscode",
				"dorzey.vscode-sqlfluff",
				"bastienboutonnet.vscode-dbt",
				"butchland.vscode-dbt-bigquery-power-user"
			]
		}
	}
}

```

Workflow:
```
- name: Run git hooks on changed files
        uses: devcontainers/ci@v0.3.1900000328
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/client_secrets.json
        with:
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: ${{ env.DATASET }}.gh-${{ github.run_id }}.${{ needs.pre-build.outputs.run_attempt }}
          runCmd: |
              cp ../artifacts/manifest.json manifest.json
              pre-commit run --files ${{ steps.parsed-changed-paths.outputs.paths }}

      - name: Run dbt test
        uses: devcontainers/ci@v0.3
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/client_secrets.json
        with:
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: ${{ env.DATASET }}.gh-${{ github.run_id }}.${{ needs.pre-build.outputs.run_attempt }}
          runCmd: |
              cp ../artifacts/manifest.json manifest.json
              dbt test -m state:modified+ --defer --state .
 ```
