### ISSUE TITLE
Support for Docker build arguments

### ISSUE THREAD

**Issue by lukin0110** [devcontainers/ci#270]
To test a python package I'm using a matrix build and I want to be able to build different `devcontainer` images for different python versions. In order to that I need to be able to specify the python version at build time.

Possible example syntax:
```yml
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    name: Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build DevContainer
        uses: devcontainers/ci@v0.3
        with:
          buildArgs:
            PYTHON_VERSION: ${{ matrix.python-version }}
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}:${{ matrix.python-version }}
          imageTag: ${{ matrix.python-version }}
          push: always

      ...
 ```
 
I can open a merge request to implement this solution if we agree on the approach.

**Comment by huxuan** [comment]
+1 for almost the same requirements.

**Comment by huxuan** [comment]
Seems this can be done with a combination of `build.args` in `devcontainer.json` and `env` in GitHub Actions. Related code snippets are like the following:

```json
{
    "build": {
        "args": {
            "PYTHON_VERSION": "${localEnv:PYTHON_VERSION}"
        },
    }
}
```

```yaml
      - uses: devcontainers/ci@v0.3
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        with:
          imageName: ghcr.io/${{ github.repository }}
          imageTag: ${{ matrix.python-version }}
```

I have an ongoing pull request for this: https://github.com/serious-scaffold/ss-python/pull/263
