### ISSUE TITLE
Unable to prebuild devcontainer image (error command docker tag)

### ISSUE THREAD

**Issue by Defman** [devcontainers/ci#271]
# Error
```
Error: Dev container build failed: Command failed: docker tag example_devcontainer_app ghcr.io/example/example-devcontainer:latest (exit code: undefined)
An error occurred building the container. Error: Command failed: docker tag example_devcontainer_app ghcr.io/example/example-devcontainer:latest
``` 

The error only occurs when trying to push the image, the simplest setup without `cacheFrom` and `push` works like a charm.

# Setup
```
.devcontainer/
├── devcontainer.json
├── docker-compose.yaml
└── Dockerfile
```

```yaml
  build:
    name: Build
    runs-on: 16cores
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/example/example-devcontainer
          cacheFrom: ghcr.io/example/example-devcontainer
          push: always
```

**Comment by onedr0p** [comment]
I have the same issue:

```
Dev container build failed: Command failed: docker tag vsc-flux-cluster-template-4e21694e9925a5c8755fd5fcba59eadc1f9d0c5b2a7d26a4ed5207ad79324fac-features ghcr.io/onedr0p/flux-cluster-template/devcontainer:latest (exit code: undefined)
```

```yaml
jobs:
  publish-devcontainer:
    name: Publish devcontainer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64 # ,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          imageTag: latest
          platform: linux/amd64 # ,linux/arm64
          configFile: .devcontainer/devcontainer.build.json
          push: always
```

**Comment by onedr0p** [comment]
Maybe a duplicate? https://github.com/devcontainers/ci/issues/191

**Comment by chrmarti** [comment]
Fixed in the Dev Containers CLI 0.57.0. The CI action will automatically pick up that version.

**Comment by mintuhouse** [comment]
This error still happens for me
```
About to run devcontainer build --workspace-folder /home/runner/work/rhythms/rhythms --config /home/runner/work/rhythms/rhythms/.devcontainer/mlai/devcontainer.json --image-name ghcr.io/GetRhythms/rhythms/rhythms-mlai-dev-mintuhouse/ruff:latest --cache-from ghcr.io/GetRhythms/rhythms/rhythms-mlai-dev-mintuhouse/ruff:latest --cache-from ghcr.io/GetRhythms/rhythms/rhythms-mlai-dev-main
  [2024-05-07T23:37:31.996Z] @devcontainers/cli 0.60.0. Node.js v18.20.2. linux 6.5.0-1018-azure x64.
```

 `Error: Dev container build failed: Command failed: docker tag mlai_mlai ghcr.io/GetRhythms/rhythms/rhythms-mlai-dev-mintuhouse/ruff:latest (exit code: undefined)`
 
 ```
 devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true # https://github.com/devcontainers/ci/issues/191#issuecomment-1603857155
        with:
          configFile: .devcontainer/mlai/devcontainer.json
          cacheFrom: ghcr.io/${{ github.repository }}/rhythms-mlai-dev-main
          imageName: ghcr.io/${{ github.repository }}/rhythms-mlai-dev-${{github.ref_name}}
          # imageTag: ${{ env.IMAGE_TAG }}
          # platform: linux/amd64,linux/arm64
          skipContainerUserIdUpdate: true
 ```
