### ISSUE TITLE
devcontainers/ci@v0.3 return "::error::Unable to locate executable file: docker."

### ISSUE THREAD

**Issue by alanlivio** [devcontainers/ci#275]
I am trying to use the devcontainers/ci@v0.3 action (see workflow and devcontainer below).
I am running it in a local environment using nektos act before run at Github (see log bellow).
However, I got the error "::error::Unable to locate executable file: docker."
Am I missing something?

`.github/workflows/hugo.yml`
```
name: deploy-hugo-to-ghpages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build at devcontainer 
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            hugo --gc  --minify
```

`.devcontainer.json`
```
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.128.0/containers/hugo
{
	"name": "Hugo",
	"image": "mcr.microsoft.com/devcontainers/base:ubuntu", // Any generic, debian-based image.
	"features": {
		"ghcr.io/devcontainers/features/go:1": {},
		"ghcr.io/devcontainers/features/hugo:1": {
			"version": "0.119.0",
			"extended": true
		},
	},
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [
		1313
	]
}
```

`gh act -W .github/workflows/hugo.yml`
```
[deploy-hugo-to-ghpages/build] 🚀  Start image=node:16-buster-slim
INFO[0000] Parallel tasks (0) below minimum, setting to 1
[deploy-hugo-to-ghpages/build]   🐳  docker pull image=node:16-buster-slim platform= username= forcePull=true
INFO[0001] Parallel tasks (0) below minimum, setting to 1
[deploy-hugo-to-ghpages/build]   🐳  docker create image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[deploy-hugo-to-ghpages/build]   🐳  docker run image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[deploy-hugo-to-ghpages/build]   ☁  git clone 'https://github.com/devcontainers/ci' # ref=v0.3
[deploy-hugo-to-ghpages/build] ⭐ Run Main Checkout
[deploy-hugo-to-ghpages/build]   🐳  docker cp src=/home/alan/src/websites/alanlivio.github.io/. dst=/home/alan/src/websites/alanlivio.github.io
[deploy-hugo-to-ghpages/build]   ✅  Success - Main Checkout
[deploy-hugo-to-ghpages/build] ⭐ Run Main Build at devcontainer
[deploy-hugo-to-ghpages/build]   🐳  docker cp src=/home/alan/.cache/act/devcontainers-ci@v0.3/ dst=/var/run/act/actions/devcontainers-ci@v0.3/
[deploy-hugo-to-ghpages/build]   🐳  docker exec cmd=[node /var/run/act/actions/devcontainers-ci@v0.3/github-action/run-main.js] user= workdir=
| Starting...
[deploy-hugo-to-ghpages/build]   ❗  ::error::Unable to locate executable file: docker. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[deploy-hugo-to-ghpages/build]   ❌  Failure - Main Build at devcontainer
[deploy-hugo-to-ghpages/build] exitcode '1': failure
[deploy-hugo-to-ghpages/build] 🏁  Job failed
Error: Job 'build' failed
```
