### ISSUE TITLE
"Everything in one step" approach clashes with workflows where the dev container is treated as one target platform.

### ISSUE THREAD

**Issue by dabrahams** [devcontainers/ci#281]
It's awkward that, if there are 10 linearly-dependent steps to testing my project, I have to put them all into one devcontainer `runCmd` when the devcontainer is treated as a target platform in my matrix strategy.  All the other platforms get distinct workflow steps but I have to intentionally not run any of those on the dev container and instead run one unified step.

**Comment by chrmarti** [comment]
There is no GitHub action runtime inside the dev container that could execute the part of your workflow steps that should run in side the container.

You could use multiple devcontainers/ci action steps though. Does that not work as expected?

**Comment by dabrahams** [comment]
It works when it works.  I suppose if the step just modifies the filesystem, that's most of the time.  However, I still can't describe my CI process in one way that works both on the devcontainer and natively, which means I either need to duplicate and conditionalize each step, or I separate the devcontainer testing from native platform tests.

**Comment by chrmarti** [comment]
GitHub Actions support running a job in a container: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

There is currently no support for dev containers for this, but that seems to be the direction you would like us to go.

**Comment by dabrahams** [comment]
That sounds promising indeed!

**Comment by dabrahams** [comment]
Another possibility would be to provide a `shell:` setting that causes a `run` command to run in the devcontainer.  That would cover most of my problems.

**Comment by chrmarti** [comment]
Maybe the custom shell support could be used for doing this: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#custom-shell

I guess currently you might need a helper script to act as the custom shell to make it work.

**Comment by adamscybot** [comment]
Well folks. I figured it out!

I'll leave comments below inline to explain thigns.

```
      - name: Start Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/example/example-image
          # You must have a runCmd defined, so just do a simple echo. Without it, the decontainers/ci action will not start the container.
          # Crucially the container is left running which is useful for what we want to do.
          runCmd: echo "Container started"

      - name: Example Step
        # We use a YAML anchor so we don't have to repeat this long string if we want several steps.
        # This runs the script in the steps via the devcontainer exec CLI, which interacts with the existing
        # running container.
        shell: &devcontainer-shell /usr/bin/bash -e -c "devcontainer exec --workspace-folder . bash -e - < '{0}'"
        run: |
          echo "I am executing inside the dev container!"

      - name: Another Step
        # Reference previously defined anchor
        shell: *devcontainer-shell
        run: echo "I am another step executing in the container!"
```
