### ISSUE TITLE
Set image digest in output

### ISSUE THREAD

**Issue by mmalyska** [devcontainers/ci#286]
I need to have pushed image digest so it can be signed with [cosign](https://github.com/sigstore/cosign).
Example action step:
```
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
```
