### ISSUE TITLE
`postStartCommand` in devcontainer.json not being run

### ISSUE THREAD

**Issue by savvn001** [devcontainers/ci#287]
Does the `postStartCommand` in devcontainer.json get run at all? It doesn't seem to be run for me through github actions. Although it works fine when I start the devcontainer through VSCode extension.

Using the latest version:

```
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3.1900000348
        with:
          noCache: true
          push: never
          runCmd: chmod +x ./ci_run_all_tests.sh && ./ci_run_all_tests.sh
```
