### ISSUE TITLE
Unable to set output inside a devcontainer

### ISSUE THREAD

**Issue by ffMathy** [devcontainers/ci#289]
When using the new non-deprecated way of setting outputs in GitHub Actions ( https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ ), it is not working. I assume it is because `$GITHUB_OUTPUT` refers to some file or pipe which is not set in the devcontainer.

```yaml
    - name: Execute DevContainer commands
      uses: devcontainers/ci@v0.3.1900000349
      with:
        runCmd: |
          echo "foo=bar" >> $GITHUB_OUTPUT
```

Now, I would expect the output `foo` to be available and usable in other steps or jobs, but it is not.
