### ISSUE TITLE
bash .i as runCmd not working

### ISSUE THREAD

**Issue by behrica** [devcontainers/ci#291]
In my dev container I need to run the `clj` command in an **interactive** bash, so I try

```yaml
steps:
    - uses: actions/checkout@v4
    - name: Run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:    
               push: never
               runCmd: bash -i -c "clj -X:test"
```

but it does no work. I don't get an error, but it drops into an interactive `clj` shell, which comes when calling
`clj` without any params.
Same with single quotes:

```yaml
steps:
    - uses: actions/checkout@v4
    - name: Run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:    
               push: never
               runCmd: bash -i -c 'clj -X:test'
```
