### ISSUE TITLE
Ability to define steps within the plugin

### ISSUE THREAD

**Issue by kamiljano** [devcontainers/ci#293]
I have a number of operations that I would like to execute within the container. There are node tests, linting, type checking, building, python tests and linting and type checking... that's arguably a lot of stuff. Yet, currently everything goes into a single step in GitHub actions - the container build step. 

Rather than define everything in the `runCmd` property, I would like to be able to define basic steps as

```
steps:
   - name: Run node tests
      run: pnpm run test
   - name: Linting
      run: pnpm run lint
   ...
```

And that would end up in separate steps within GitHub actions.

**Comment by sireeshajonnalagadda** [comment]
Hi @kamiljano, 
Thank you for reaching out! 

That makes sense! You want to modularize your GitHub Actions workflow by breaking down your current runCmd monolithic script into separate, easily understandable steps. By doing this, you can better organize and manage each task individually, as well as improve readability and debugging in case something fails.

You can define your steps in the workflow.yml file under the jobs section. Here’s an approach where each operation (node tests, linting, Python tests, etc.) is defined in separate steps.

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: your-container-image:latest  # Replace with your container image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js related tasks
      - name: Install Node dependencies
        run: pnpm install

      - name: Run Node tests
        run: pnpm run test
 # Additional build or deployment steps can go here

Hope this info helps you define the steps! 
Please feel free to reach out again in case of any further queries. 

Thanks, 
Sireesha

**Comment by adamscybot** [comment]
I have just now figured out a way to achieve this! I have posted it over on [this issue](https://github.com/devcontainers/ci/issues/281) (which is the same I think). But will also now post here for posterity:

```
      - name: Start Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/example/example-image
          # You must have a runCmd defined, so just do a simple echo. Without it, the decontainers/ci action will not start the container.
          # Crucially the container is left running which is useful for what we want to do.
          runCmd: echo "Container started"

      - name: Example Step
        # We use a YAML anchor so we don't have to repeat this long string if we want several steps.
        # This runs the script in the steps via the devcontainer exec CLI, which interacts with the existing
        # running container.
        shell: &devcontainer-shell /usr/bin/bash -e -c "devcontainer exec --workspace-folder . bash -e - < '{0}'"
        run: |
          echo "I am executing inside the dev container!"

      - name: Another Step
        # Reference previously defined anchor
        shell: *devcontainer-shell
        run: echo "I am another step executing in the container!"
```
