### ISSUE TITLE
runCmd exit code is ignored

### ISSUE THREAD

**Issue by choopm** [devcontainers/ci#294]
~I noticed a bug when using the action like this:~

```yaml
- name: Build and run dev container task
  uses: devcontainers/ci@v0.3
  with:
    imageName: ghcr.io/${{ github.repository }}-devcontainer
    cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
    push: always
    runCmd: |
      echo foo
      false
      echo bar
```

Exit codes will be ignored and thus commands after any failed one will still be executed.
~There is no option to get the actual exit code afterwards.~

```log
🚀 Run command in container
  About to run devcontainer exec --workspace-folder /home/runner/work/xxx/xxx --remote-env GITHUB_OUTPUT=/mnt/github/output --remote-env GITHUB_ENV=/mnt/github/env --remote-env GITHUB_PATH=/mnt/github/path --remote-env GITHUB_STEP_SUMMARY=/mnt/github/step-summary bash -c echo foo
  false
  echo bar
  foo
  bar
```

~This is caused by these lines of code:~
 - ~https://github.com/devcontainers/ci/blob/4432f30fa0aae55f8a1691ee792447503218135f/github-action/src/exec.ts#L10~
 - ~https://github.com/devcontainers/ci/blob/4432f30fa0aae55f8a1691ee792447503218135f/github-action/src/exec.ts#L13~

~It seems this can be fixed by switching from `getExecOutput()` to `exec()` according to https://github.com/actions/toolkit/issues/1615~
