### ISSUE TITLE
devcontainer ci image cache is never working

### ISSUE THREAD

**Issue by crimsonvspurple** [devcontainers/ci#302]
In dc github action I have

```
      - name: Dev Container Build and Run Action
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainers
          imageTag: latest
          runCmd: |
            mvn --version
            whoami
            ls -lash /home/vscode
            echo "Dev Container can start up! Let's push!"
```

this builds and pushes the DC.

In deploy github action I have:

```
      - name: Dev Container Build and Run Action
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainers
          cacheFrom: ghcr.io/${{ github.repository_owner }}/devcontainers
          # platform: linux/amd64,linux/arm64
          push: never
          runCmd: |
            whoami
            ls -lash /home/vscode/
< then a lot more things>
```

This always rebuilds the container instead of loading it from cache.

What am I doing wrong?

**Comment by sebst** [comment]
See #300

**Comment by neilenns** [comment]
Has anyone actually managed to get this to work recently? I've read both the above issues and the blog post and still cannot get this to work in my CI workflow.

I'm trying to build a devcontainer image that is then used by the repo's docker-compose.yaml to set up a multi-container development environment. The files to build the apps (primary) image are under .devcontainer/apps:

![Image](https://github.com/user-attachments/assets/8d464d8a-0cd6-4807-86e2-8a82577c5526)

It builds perfectly fine in CI, but I *cannot* get caching to work at all:

```yaml
      - name: Build dev container
        if: steps.changed-files.outputs.devcontainer_any_changed == 'true'
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}-devcontainer
          cacheTo: type=registry,ref=ghcr.io/${{ github.repository }}-devcontainer-gha:cache
          configFile: .devcontainer/apps/devcontainer.json
          refFilterForPush: refs/heads/main
          push: filter
```

This results in:

```
[2025-04-21T15:04:18.609Z] ERROR: Cache export is not supported for the docker driver.
  Switch to a different driver, or turn on the containerd image store, and try again.
  Learn more at https://docs.docker.com/go/build-cache-backends/
```

My CI runs on `ubuntu-latest`
